# name your GitHub workflow
name: Run Python Tests

# define your GitHub workflow trigger and run frequency
on:
  push:
    branches:
      - main

# declaring your jobs and steps
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout our repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Install Python Dependencies using Poetry
    # Run Pytest cases